name: Deploy to EC2 Instance
# 언제 작동을 시킬지
on:
  workflow_dispatch:
  push:
    branches:
      - main

    paths:
      - 'airflow/dags/**'


# 어떤 job을 할지
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          script: |
            cd /home/ubuntu/mlops_pipeline1/airflow/dags
            git pull



